version: '3.8'

services:
  test-agent:
    image: test-running-agent:test
    container_name: test-agent-compose
    environment:
      - NODE_ENV=test
    ports:
      - "3456:3456"
    volumes:
      - ../docker/test-config.json:/workspace/test-agent.config.json:ro
    command: node dist/index.js start --config /workspace/test-agent.config.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3456/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    container_name: test-postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  default:
    name: test-agent-network